### ISSUE TITLE
記事数が多いと目的の記事を探すのが大変なときがある

### ISSUE THREAD

**Issue by januswel** [zenn-dev/zenn-vscode-extension#108]
次の 2 点が揃うと目的の記事を探すのが大変

1. この extension が記事を content URL 順に表示している
2. slug を自動生成している

例えば、次の状態で「Technology Radar Volume 30 まとめ」を探すのに時間がかかってしまう

<img width="240" alt="Zenn VSCode extension スクショ" src="https://github.com/zenn-dev/zenn-vscode-extension/assets/43239/4dfbab20-0767-44a6-a95b-0b67d5d5ce88">

**Comment by cm-wada-yusuke** [comment]
たしかにこのようなケースはありそうです。お手数ですがVSCodeの全文検索でカバーいただければと思います :bow:

**Comment by januswel** [comment]
コメントありがとうございます
確認漏れてました

> VSCodeの全文検索でカバー

承知です
これ閉じますね
