### ISSUE TITLE
機能改善：ワークスペースを開いていないというエラー通知はなくてもよいのではないか

### ISSUE THREAD

**Issue by senkenn** [zenn-dev/zenn-vscode-extension#110]
Zennサポーターの皆様お疲れ様です。おかげさまで活用させていただいてます。

新規でVSCodeウィンドウを立ち上げるとこのようなエラーメッセージが表示されると思います
![image](https://github.com/zenn-dev/zenn-vscode-extension/assets/65453007/93c5f11c-5265-4931-98f1-15496167b0e8)

当たり前ですが、Zenn記事を書きたいとき以外にもウィンドウを開くことは多いので、毎回出すのは過剰な気がします。

拡張機能をインストールした初回のみ通知、もしくはいっそワークスペースを開いていない場合はサポート外としてエラー通知はなくても良いのではないかと思います。

**Comment by cm-wada-yusuke** [comment]
たしかにそのとおりですね。エラー通知はなくてもよさそうです。ありがとうございます。

**Comment by senkenn** [comment]
PR作ります
