### ISSUE TITLE
[Bug] Codespace 上で〈記事を新規作成〉を押すとエラーが出る

### ISSUE THREAD

**Issue by Ningensei848** [zenn-dev/zenn-vscode-extension#4]
> Error running command zenn-preview.new-article: command 'zenn-preview.new-article' not found. This is likely caused by the extension that contributes zenn-preview.new-article.

拡張機能のインストール自体は成功するが、Articles 横にあるボタンを押すと、右下にエラーメッセージが表示される

<img width="352" alt="image" src="https://user-images.githubusercontent.com/20794309/200490003-5c83e754-3a08-4eb5-991e-c6392ff7fc95.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/20794309/200490089-35629426-ca90-4507-96ed-d8b571c9e3cc.png">

**Comment by uttk-dev** [comment]
@Ningensei848 

バグ報告ありがとうございます。
正式版では対応したいと思いますが、まだ β 版ということもあり、
基本的な動作や機能の開発を進めていきたいと思っています。

そのため、対応が遅れる可能性がありますので、その点をご留意いただければと思います。

**Comment by uttk-dev** [comment]
管理しやすくするために #13 に集約して管理することにしました。
そのため、この Issue はクローズさせて頂きます。
何か新たな問題を見つけた場合は、上記の Issue に報告頂ければと思います。
