### ISSUE TITLE
スニペットを追加する

### ISSUE THREAD

**Issue by HRTK92** [zenn-dev/zenn-vscode-extension#40]
Zennで使われている独自の記法をスニペットに追加することで記事を書くのがスムーズになると思いました。

スニペットの例としては、[VSCodeでスニペットを活用しZennの記事執筆を楽にする](https://zenn.dev/melon1891/articles/vsc_snippets)や
```
@[tweet]($1)
@[gist]($1)
```
このようなものがあるとうれしいです。

[Snippet Guide](https://code.visualstudio.com/api/language-extensions/snippet-guide)

もしよければPRを送ってもよろしいでしょうか

**Comment by uttk-dev** [comment]
@HRTK92 

提案ありがとうございます！
PR は大歓迎です！
何か分からないところなどあればお気軽にお声がけ下さい！

**Comment by HRTK92** [comment]
了解です！

時間があれば今週中に送ろうと思います

**Comment by HRTK92** [comment]
了解です！
近いうちにPRを送らせていただきます。

**Comment by uttk-dev** [comment]
@HRTK92 

先ほど https://github.com/zenn-dev/zenn-vscode-extension/pull/41 をマージしました。
リリースについては来週リリースしたいと思いますので、この Issue もその時にクローズしたいと思います。
よろしくお願いします。

**Comment by HRTK92** [comment]
わかりました！
丁寧に対応していただきありがとうございました

**Comment by uttk-dev** [comment]
@HRTK92 

先ほど、v0.0.6 ( https://github.com/zenn-dev/zenn-vscode-extension/pull/39 ) をリリースしましたので、この Issue をクローズしたいと思います。ありがとうございました 🙏
