### ISSUE TITLE
Bookのプレビュー表示でサマリー項目がZenn-cliと異なる表示になる

### ISSUE THREAD

**Issue by yo-goto** [zenn-dev/zenn-vscode-extension#49]
Book のプレビュー画面において summary の項目が改行、空白行等がある場合に zenn-cli との表示が異なる現象を見つけました。`symmary` の文字列を以下のようなパターンにすると zenn-cli では改行が反映されるのに対して、vscode-extension では反映されません。

```yaml
# パターン(1)
summary:
  ○○○○○


  ○○○○○


  ○○○○○
```

```yaml
# パターン(2)
summary: |
  ○○○○○

  ○○○○○

  ○○○○○
```

![img_zenn-cli-vs-vscode-ext-1](https://user-images.githubusercontent.com/50942816/214763652-241356e7-079c-41fd-bc8e-cad62ab5c32c.jpg)

特にダブルクォーテーション(`""`)で囲んでいる場合にはエラーとなり、タイトル等が表示されなくなります。

```yaml
# パターン(3)
summary: "
○○○○○
\n\n
○○○○○
\n\n
○○○○○
"
```

![img_zenn-cli-vs-vscode-ext-2](https://user-images.githubusercontent.com/50942816/214764189-4ef1cf62-7de6-4dd1-9e5e-a834d78614dd.jpg)

これは zenn-cli の方では起こらず、Web 上でも正確に表示されています。サマリーでは複数行で改行したい場合もあるので、このようなフォーマットも正しく表示されるのが望ましいと思いました。

そこで実際に zenn-cli との違いを調査してみたところ、二点の問題がありました。

1. zenn-cli で利用されている YAML パーサーは js-yaml の [`load()`](https://github.com/nodeca/js-yaml#load-string---options-) メソッドで extension の方で利用されている yaml パッケージの [`parse()`](https://eemeli.org/yaml/#parse-amp-stringify) だと上のようなパターンでエラーが吐き出される
2. BookPreview の scss ファイルのスタイルで改行設定がないためエラーを回避しても改行されない

yaml で利用できる `parse()` メソッドの第二引数のオプション等調べてみましたが、エラーが吐き出されないようにする方法が見つからなかったため、とりあえず js-yaml の `load()` の方に置換した上でスタイルを調整することでうまく表示されるようになりました。PR を作成してみたので検討してみてください。何か改善点などあれば教えていただけると助かります。

**Comment by uttk-dev** [comment]
@yo-goto 

PR ありがとうございました！マージさせて頂きました。
リリースついては来週を予定しています。
それまではリリース済みの拡張をご利用下さい。

よろしくお願いします。

**Comment by yo-goto** [comment]
マージありがとうございます！
楽しみにしています👍

**Comment by uttk-dev** [comment]
@yo-goto 

先ほど v0.0.9 をリリースしましたので、最新バージョンで修正内容をご利用いただけます。
リリース内容については以下の PR からご確認ください。

https://github.com/zenn-dev/zenn-vscode-extension/pull/56

よろしくお願いします。
