### ISSUE TITLE
[Bug] Codespace 上で〈記事一覧を更新〉を押すとエラーが出る

### ISSUE THREAD

**Issue by Ningensei848** [zenn-dev/zenn-vscode-extension#5]
> Error running command zenn-preview.refresh-articles: command 'zenn-preview.refresh-articles' not found. This is likely caused by the extension that contributes zenn-preview.refresh-articles.

拡張機能のインストール自体は成功するが、Articles 横にあるボタンを押すと、右下にエラーメッセージが表示される

<img width="352" alt="image" src="https://user-images.githubusercontent.com/20794309/200490003-5c83e754-3a08-4eb5-991e-c6392ff7fc95.png">

<img width="478" alt="image" src="https://user-images.githubusercontent.com/20794309/200490622-5e760110-3fdc-44db-bd07-fe02f4997f97.png">

**Comment by uttk-dev** [comment]
管理しやすくするために #13 に集約して管理することにしました。
そのため、この Issue はクローズさせて頂きます。
何か新たな問題を見つけた場合は、上記の Issue に報告頂ければと思います。
