### ISSUE TITLE
チャプターの新規作成コマンドの追加

### ISSUE THREAD

**Issue by yo-goto** [zenn-dev/zenn-vscode-extension#52]
本のチャプターを作成する過程で「記事を新規作成」するのと同じように「チャプターを新規作成」のようなチャプター単体で作成するコマンドが必要であるのではないかなと感じました。チャプターを作成する本の候補がサジェストされてからスラグの入力プロンプトが表示されるのが一つのケースかなと考えています。

![img_zenn-ext-select-book](https://user-images.githubusercontent.com/50942816/215275630-0f918b53-8fbc-4bc5-be2c-858b93dee04c.jpg)

また、以下のように TreeView を展開しているときにBOOKSの場所からスムーズにチャプターを作成できると使いやすいと感じました。
![img_zenn-ext-make-chapter](https://user-images.githubusercontent.com/50942816/215275589-031c81d5-c0b0-4029-84c0-acff2d6d042a.png)

新規機能、特に TreeView からの作成ボタンなどについては実装する場合には議論が必要になるかと思いますが、さっそく自分でPRを作ってみたので検討してみてください🙇‍♂️

**Comment by uttk-dev** [comment]
提案ありがとうございます。PR の方をマージさせて頂きました。
機能のリリースについては近々実施予定なので、しばらくお待ち頂ければと思います。
よろしくお願いします。

**Comment by yo-goto** [comment]
記載していなかったドキュメント用記述のための画像です。

![img_zenn-ext-guide-doc-kai](https://user-images.githubusercontent.com/50942816/219618637-062f04d4-86dd-4a50-b7b1-9cb31f8b7274.jpg)
