### ISSUE TITLE
ガイドページ一覧の追加

### ISSUE THREAD

**Issue by yo-goto** [zenn-dev/zenn-vscode-extension#55]
連続で issue 立てちゃってすみません。
機能提案というか、zenn-cli にある機能で表示されているガイドのページがvscodeの方でも見られると嬉しいかなと感じました。特にマークダウン記法とかは書いている途中に確認したいときがあるのですぐに見れるといいかなと思います。
![img_zenn-ext-cli-guidepages](https://user-images.githubusercontent.com/50942816/215449884-775c71a3-04a2-434f-b9c7-9581886136ff.png)

まだPRできるコードではないのですが、イメージ的にはガイドのセクションが Treeviewの下に展開されて、クリックするとWebviewにzenn API からフェッチされた記事が表示されるというような感じが一つのケースかなと(あるいは外部リンクで直接的にWeb上の記事に飛ばされる)。
![img_zenn-ext-guidetree](https://user-images.githubusercontent.com/50942816/215450415-1cf572e4-6efc-47f6-8c1d-03e137058188.jpg)

**Comment by cm-wada-yusuke** [comment]
おお、ありがとうございます！楽な方法でいいかなと思うので、外部リンクで飛ぶのがよさそうと思いました。

**Comment by uttk-dev** [comment]
>楽な方法でいいかなと思うので、外部リンクで飛ぶのがよさそうと思いました。

個人的には、ローカルのVSCode ( github.dev じゃない場合 )でも見やすいように WebView で表示しちゃうのはアリだと思いました。

**Comment by uttk-dev** [comment]
と思いましたが、zenn は iframe ( WebView ) で 表示できなかった記憶があるので、やっぱり外部リンクの方が良さそうかもですね。はい。

**Comment by yo-goto** [comment]
レンダリング自体は Preview を使いまわすことでできそうでしたが、zenn api へのデータフェッチで CORS エラーが発生してブロックされちゃうので、簡単な外部リンクに飛ばすバージョンでまずはPRを作ってみます👍

**Comment by yo-goto** [comment]
ドキュメント用に作成したイメージ画像です。

背景あり | 背景なし
--|--
![img_zenn-ext-guide-doc-back](https://user-images.githubusercontent.com/50942816/216012856-d58e402f-bf73-41f4-a92d-ac85ea2b4cd2.jpg) | ![img_zenn-ext-guide-doc-no-back](https://user-images.githubusercontent.com/50942816/216012827-6c04d733-fff7-4935-8744-89a16c509834.jpg)
