### ISSUE TITLE
[Bug] Codespace 上で〈本を新規作成〉を押すとエラーが出る

### ISSUE THREAD

**Issue by Ningensei848** [zenn-dev/zenn-vscode-extension#6]
> Error running command zenn-preview.new-book: command 'zenn-preview.new-book' not found. This is likely caused by the extension that contributes zenn-preview.new-book.

拡張機能のインストール自体は成功するが、Books 横にあるボタンを押すと、右下にエラーメッセージが表示される

<img width="352" alt="image" src="https://user-images.githubusercontent.com/20794309/200490003-5c83e754-3a08-4eb5-991e-c6392ff7fc95.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/20794309/200491011-d5dcd8b2-ae95-4730-bc72-c0994bd0ef6a.png">

**Comment by uttk-dev** [comment]
管理しやすくするために #13 に集約して管理することにしました。
そのため、この Issue はクローズさせて頂きます。
何か新たな問題を見つけた場合は、上記の Issue に報告頂ければと思います。
