### ISSUE TITLE
Zenn Previewで本の目次のリンクが反応しない

### ISSUE THREAD

**Issue by kboy-silvergym** [zenn-dev/zenn-vscode-extension#70]
いつもありがとうございます！

Zenn Previewを入れて、zenn本をgithub.devでプレビューするという利用方法をしているのですが、最近本のChapter一覧から各ページへ飛べなくなっていまいました。ページごとに開くことはできるのですが、目次から飛べなくて少し不便です。

何卒ご確認の程よろしくお願い致します！:bow:

https://user-images.githubusercontent.com/17683316/218235968-1f1591a5-1d30-4df5-bbf3-751a64199349.mov

**Comment by uttk-dev** [comment]
@kboy-silvergym 

バグ報告ありがとうございます。助かりました！
v0.1.0 で対応しましたので、ご確認頂ければと思います！
よろしくお願いします。

https://github.com/zenn-dev/zenn-vscode-extension/releases/tag/0.1.0

**Comment by kboy-silvergym** [comment]
@uttk-dev 
ありがとうございます！直ってました！
