### ISSUE TITLE
機能提案: zenn.dev でコンテンツを開く機能

### ISSUE THREAD

**Issue by yo-goto** [zenn-dev/zenn-vscode-extension#94]
## 提案機能

`published: true` の記事や `config.yaml` ファイルに `published: true` で定義された本そのものと、チャプターとして定義された各種のファイルに対してコマンド実行や UI ボタンクリックで Zenn.dev 上でデプロイされたコンテンツにアクセスできる機能。

## 背景

記事やチャプターを書いているときに zenn-cli や vscode 拡張でのプレビューではなく、実際にデプロイされたビューを直接見たいという場面がたまにあり、そういった場面にて現在のファイルやツリービューから直接 zenn.dev の公開コンテンツにアクセスできる機能があるとよいな思いました。

また、特定の記事についてのいいね数やコメントなどを見たいなと思った時もまず zenn.dev にアクセスして自分のアカウントページまたは管理画面から記事や本を探してアクセスしなくてはならないので少し手間であり、記事の場合は特に数が増えやすいので時間経過でさらに探すのが面倒になるのではないかと感じました。

「github.dev で開く」というボタンが zenn.dev のチャプタービューにはありますが、それとは逆に 「zenn.dev で開く」というボタンがプレビュー画面にもあると双方向での行き来が非常に楽になるとも思います。

## 機能イメージ

プロトタイプのコードはできていますが、現状まだ PR できるものではないのでなんとなくの機能要素のイメージです。

- 設定画面にzenn.devで使用しているユーザー名文字列を指定
- ツリービュー上のボタン(`publihshed: true` のコンテンツツリーアイテムのみボタンを表示)
- コマンド「Zenn: Open Content In Zenn.dev」をコマンドパレットから実行してアクティブファイルが `published: true` ならブラウザで開く
- プレビュー画面上に「zenn.dev で開く」クリックボタンを表示
- 各ルートからコマンドを実行すると、ユーザー名文字列が無いなどの状況でコマンド実行失敗

**Comment by uttk-dev** [comment]
@yo-goto 

提案ありがとうございます。
Zenn との連携を強める、とても良い機能だと思います！

まだ機能としてと入れるかは、実装してみないと分からない部分もあるので何とも言えませんが、
より便利にしたいので、少し私からも提案させてください。

<br />

- 設定画面にzenn.devで使用しているユーザー名文字列を指定

こちらは、明記はされていないですが `/links/articles/{slug}` でも記事に参照できるため、利便性を考えてユーザー名を設定しない方向にしたいです。( `/links/articles/{slug}` のようなユーザー名を使用しないリンクを使う )

<br />

- ツリービュー上のボタン(publihshed: true のコンテンツツリーアイテムのみボタンを表示)
- コマンド「Zenn: Open Content In Zenn.dev」をコマンドパレットから実行してアクティブファイルが published: true ならブラウザで開く

著者であれば、`published: false` であっても下書きとしてプレビューすることができるので、公開ステータス関係なく表示したいです。

### 懸念事項

また、少し懸念事項があったためコメントしておきます。

- 未デプロイの記事・本の場合、遷移先で 404 になってしまう
  - 一応、許容範囲な挙動だと判断
  - 可能であれば、未デプロイのファイルではプレビューできないようにしたい
  - ただ無理そうであれば、そのままの仕様でOK

**Comment by yo-goto** [comment]
フィードバックしていただきありがとうございます！

一応アクセス機能の実装とUI上のボタン配置まで実装して自分でもテストしてみたところ、使う頻度としてはプレビューよりも確実に低いなとは思うので、ツリービュー上にボタン配置とかはやりすぎでUI的に散らかってしまうかもしれないなどの懸念があります。

プレビュー画面上のボタンやコマンドとしてはあってもいいかなと思ってるんですが、そこについても可能であれば意見を伺いたいな思います！

/links/articles/{slug} の方でアクセスできたんですね。ユーザー文字列の扱いについても不安があったのでそちらのほうで調整してみます👍

404についてはちょうど考えていたところでURLが存在するかどうかを判定するzennへのリクエスト処理などを噛ませようかなと思ってます。下書きも含めてそのあたりfetchでやろうと思いますが、ガイド機能の時のようちょっと上手く行かない可能性もあります。もし出来ないなら何かしら他にも方法がないか考えてみます。

**Comment by uttk-dev** [comment]
@yo-goto 

>一応アクセス機能の実装とUI上のボタン配置まで実装して自分でもテストしてみたところ、使う頻度としてはプレビューよりも確実に低いなとは思うので、ツリービュー上にボタン配置とかはやりすぎでUI的に散らかってしまうかもしれないなどの懸念があります。
>
>プレビュー画面上のボタンやコマンドとしてはあってもいいかなと思ってるんですが、そこについても可能であれば意見を伺いたいな思います！

確かにそうですね、コマンドは問題ないと思いますが表示に関してはプレビュー画面のみでいい気がします。TreeView に表示しちゃうと間違って押しちゃうのも UX 悪くなりそうですし。

>404についてはちょうど考えていたところでURLが存在するかどうかを判定するzennへのリクエスト処理などを噛ませようかなと思ってます。下書きも含めてそのあたりfetchでやろうと思いますが、ガイド機能の時のようちょっと上手く行かない可能性もあります。もし出来ないなら何かしら他にも方法がないか考えてみます。

ありがとうございます🙏 
私の方でも色々と試してみますね。何か分かればコメントします💪

**Comment by yo-goto** [comment]
@uttk-dev 
承知しました!
ツリービューの方はなくして、コマンドとプレビュー画面の方に反映(「github.dev で表示する」みたいに新しくボタンとして表示させるか、UI 的にキレイにできそうでなれかば「公開」などの既存要素をボタンに置き換える)というような方向でやってみたいと思います!

**Comment by yo-goto** [comment]
> こちらは、明記はされていないですが /links/articles/{slug} でも記事に参照できるため、利便性を考えてユーザー名を設定しない方向にしたいです。( /links/articles/{slug} のようなユーザー名を使用しないリンクを使う )

こちらのリンクURL って `https://zenn.dev/zenn/articles/markdown-guide` という zenn の記事の URL なら  `https://zenn.dev/links/articles/markdown-guide` でリダイレクトされるっていう認識であってますか? 

`links` というユーザー名文字列を取得しているユーザーさんがいらっしゃるようなのでこのままアクセスできるようにすると、スラグなどが偶然に一致したときに不都合があるかもしれないと思ったのですが大丈夫でしょうか?

**Comment by uttk-dev** [comment]
@yo-goto 

>というのも、links というユーザー名文字列を取得しているユーザーさんがいらっしゃるようなのでこのままアクセスできるようにすると、スラグなどが偶然に一致したときに不都合があるかもしれないと思ったのですが大丈夫でしょうか?

すいません、確かにそうですね。こちら `links` では無くて、`link` が正しい URL でした。
なので、 `https://zenn.dev/zenn/articles/markdown-guide` の場合は `https://zenn.dev/link/articles/markdown-guide` になります。

また、`link` はユーザー名として設定できないため、今後スラッグが一致することなどは無いので安心してください。

**Comment by yo-goto** [comment]
@uttk-dev 
教えていただきありがとうございます!
承知しました。

**Comment by yo-goto** [comment]
@uttk-dev 
本のチャプターについての URL として `https://zenn.dev/zenn/books/how-to-create-book/viewer/about` の場合
いくつかテストしてみたのですが以下の URL ではアクセスできませんでした。

- `https://zenn.dev/link/books/how-to-create-book`
- `https://zenn.dev/link/books/how-to-create-book/viewer/about`
- `https://zenn.dev/link/books/how-to-create-book/about`
- `https://zenn.dev/link/books/about`
- `https://zenn.dev/link/chapters/about`

チャプター単体で link でアクセス可能な URL は存在していますか?

**Comment by cm-wada-yusuke** [comment]
@yo-goto チャプターをクエリで指定する形になります

https://zenn.dev/link/books/how-to-create-book?chapter_slug=getting-started

**Comment by yo-goto** [comment]
クエリ形式でチャプターは開けるんですね。
教えて頂きありがとうございます！

**Comment by uttk-dev** [comment]
対応しない方針になりました。

ref: https://github.com/zenn-dev/zenn-vscode-extension/pull/99#issuecomment-1467214604
